package de.medizininformatikinitiative.torch.rest.schema;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(name = "JobManifest", description = "FHIR Async Bulk Data manifest (TORCH variant)")
public class JobManifestSchema {
    @Schema(example = "2026-03-10T18:22:11Z")
    public String transactionTime;

    @Schema(example = "https://torch.example.org/fhir/$extract-data")
    public String request;

    @Schema(example = "false")
    public boolean requiresAccessToken;

    @Schema(description = "Artifacts generated by the job")
    public List<OutputEntrySchema> output;

    @Schema(description = "Additional TORCH extensions")
    public List<ExtensionSchema> extension;

    @Schema(
            name = "JobManifestOutput",
            description = "Output artifact produced by the extraction job"
    )
    public static class OutputEntrySchema {

        @Schema(
                description = "Download URL of the produced artifact",
                example = "https://fileserver/jobs/<jobId>/<batchId>.ndjson"
        )
        public String url;

        @Schema(
                description = """
                        Type of artifact produced by the job.
                        
                        Typical values:
                        - NDJSON Bundle (patient batch bundle)
                        - NDJSON Bundle (core bundle)
                        - Job diagnostics report (JSON)
                        """,
                example = "NDJSON Bundle"
        )
        public String type;
    }

    @Schema(name = "JobManifestExtension")
    public static class ExtensionSchema {

        @Schema(example = "https://torch.mii.de/fhir/StructureDefinition/torch-job")
        public String url;

        @Schema(
                description = "Serialized TORCH Job state (mapper.valueToTree(job))",
                implementation = TorchJobSchema.class
        )
        public TorchJobSchema valueObject;
    }
}
